# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
exclude: |
  (?x)
  \.vol
repos:
  - repo: https://github.com/stefsmeets/nbcheckorder/
    rev: v0.2.0
    hooks:
      - id: nbcheckorder
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-yapf
        additional_dependencies: [toml, yapf]
        types_or: [jupyter]
      - id: nbqa-ruff
        args: [--fix, --ignore=E402]
        types_or: [jupyter]
