[tool.ruff]
line-length = 96
target-version = "py310"
extend-include = ["*.ipynb"]

[tool.ruff.lint]
# Enable Pyflakes `E` and `F` codes by default.
select = [
	"F",  # Pyflakes
	"E",  # pycodestyle (error)
	"W",  # pycodestyle (warning)
	"I",  # isort
]
ignore = [
    "E402",  # import not at top
    "E501",  # line length too long
    "E703",  # useless semicolon
]

[tool.ruff.lint.isort]
known-first-party = ["gemdat"]
required-imports = []

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
